# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504dec891f856df58184d136a4f5d688b2beadd9cbae966d4cb48dfc8730980f0d95e0e9348cd04f4f1640bf63cf93d13ecd90ba3a7bcb3ec500c06338edd15c

test:
  secret_key_base: 45d01307f3ca7c327726e31983065643e52052fd79ec340976a1c7c5209abd39cecc303cd36b65e2c309127f46822d37411c62cbdc163d7f89d7cb872eacb964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
